# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='TestProto',
  serialized_pb=_b('\n\ntest.proto\x12\tTestProto\"5\n\x06Struct\x12\x15\n\rstruct_string\x18\x01 \x02(\t\x12\x14\n\x0cstruct_int32\x18\x02 \x02(\x05\"\xc4\x01\n\x04Test\x12\x14\n\x0ctest_int32_1\x18\x01 \x02(\x05\x12\x14\n\x0ctest_int32_2\x18\x02 \x02(\x05\x12\x14\n\x0ctest_int32_3\x18\x03 \x02(\x05\x12\x15\n\rtest_string_1\x18\x04 \x02(\t\x12\x15\n\rtest_string_2\x18\x05 \x01(\t\x12\x15\n\rtest_string_3\x18\x06 \x02(\t\x12\x12\n\ntest_array\x18\x07 \x03(\t\x12!\n\x06struct\x18\x08 \x03(\x0b\x32\x11.TestProto.Struct')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STRUCT = _descriptor.Descriptor(
  name='Struct',
  full_name='TestProto.Struct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='struct_string', full_name='TestProto.Struct.struct_string', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='struct_int32', full_name='TestProto.Struct.struct_int32', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=78,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='TestProto.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_int32_1', full_name='TestProto.Test.test_int32_1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_int32_2', full_name='TestProto.Test.test_int32_2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_int32_3', full_name='TestProto.Test.test_int32_3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_string_1', full_name='TestProto.Test.test_string_1', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_string_2', full_name='TestProto.Test.test_string_2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_string_3', full_name='TestProto.Test.test_string_3', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_array', full_name='TestProto.Test.test_array', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='struct', full_name='TestProto.Test.struct', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=277,
)

_TEST.fields_by_name['struct'].message_type = _STRUCT
DESCRIPTOR.message_types_by_name['Struct'] = _STRUCT
DESCRIPTOR.message_types_by_name['Test'] = _TEST

Struct = _reflection.GeneratedProtocolMessageType('Struct', (_message.Message,), dict(
  DESCRIPTOR = _STRUCT,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestProto.Struct)
  ))
_sym_db.RegisterMessage(Struct)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestProto.Test)
  ))
_sym_db.RegisterMessage(Test)


# @@protoc_insertion_point(module_scope)
